export interface MenuItem {
  id: number;
  name: string;
  price: number;
  is_available: boolean;
  category: string;
  position?: number; // Added position field
}

export interface OrderItem extends MenuItem {
  quantity: number;
}

export interface Order {
  id: string;
  order_number: string;
  items: OrderItem[];
  total: number;
  status: 'pending' | 'preparing' | 'ready' | 'served' | 'cancelled';
  order_time: string;
  updated_time?: string;
}

export interface CreateOrderRequest {
  order_number?: string; // Made optional as it will be generated by the API
  items: OrderItem[];
  total: number;
}

export interface UpdateOrderRequest {
  items?: OrderItem[];
  total?: number;
  status?: Order['status'];
}