'use client';

import React, { useState, useEffect, useRef } from 'react';
import { Clock, ChefHat, Edit2, Trash2, X, Save, BarChart3 } from 'lucide-react';
import { Order, MenuItem, OrderItem, CreateOrderRequest, UpdateOrderRequest } from '@/types';

const CafeOrderSystem = () => {
  const [orders, setOrders] = useState<Order[]>([]);
  const [menuItems, setMenuItems] = useState<MenuItem[]>([]);
  const [buildingOrder, setBuildingOrder] = useState<OrderItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [dailySales, setDailySales] = useState(0);
  const [pendingOrdersCount, setPendingOrdersCount] = useState(0);
  const [editingOrder, setEditingOrder] = useState<Order | null>(null);
  const [viewingOrder, setViewingOrder] = useState<Order | null>(null);
  
  // Sales report modal state
  const [isReportModalOpen, setIsReportModalOpen] = useState(false);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [salesReport, setSalesReport] = useState<any>(null);

  const closeOrderPopup = () => {
    setViewingOrder(null);
  };
  
  const handleOrderClick = (order: Order) => {
    setViewingOrder(order);
  };

  // Fetch menu items and set up real-time updates
  useEffect(() => {
    fetchMenu();
    fetchOrders();
    
    // Set up polling for real-time updates
    const pollingInterval = setInterval(() => {
      fetchOrders();
    }, 3000); // Poll every 3 seconds
    
    // Clean up interval on component unmount
    return () => clearInterval(pollingInterval);
  }, []);

  const fetchMenu = async () => {
    try {
      const response = await fetch('/api/menu');
      if (!response.ok) throw new Error('Failed to fetch menu');
      const data = await response.json();
      setMenuItems(data);
    } catch (err) {
      setError('Failed to load menu');
      console.error(err);
    }
  };

  const fetchDailySales = async () => {
    try {
      const response = await fetch('/api/daily-sales/today');
      if (!response.ok) throw new Error('Failed to fetch daily sales');
      const data = await response.json();
      setDailySales(data.total_revenue);
    } catch (err) {
      console.error('Failed to fetch daily sales:', err);
      setDailySales(0); // Reset to 0 on error
    }
  };

  const ordersContainerRef = useRef<HTMLDivElement>(null);

  const fetchOrders = async () => {
    const scrollPosition = ordersContainerRef.current?.scrollTop || 0; // Store current scroll position
    try {
    const response = await fetch('/api/orders'); // Remove ?includeServed=true to only get non-served orders
    if (!response.ok) throw new Error('Failed to fetch orders');
    const data = await response.json();
    setOrders(data);
    
    // Calculate pending orders count (orders that are not served)
    const pendingOrders = data.filter((order: Order) => order.status !== 'served');
    setPendingOrdersCount(pendingOrders.length);
    
    // Fetch daily sales from API instead of calculating locally
    await fetchDailySales();
    
    setLoading(false);
    
    if (ordersContainerRef.current) {
        ordersContainerRef.current.scrollTop = scrollPosition; // Restore scroll position
    }
    } catch (err) {
      setError('Failed to load orders');
      setLoading(false);
      console.error(err);
    }
  };

  const addToOrder = (item: MenuItem, quantity: number) => {
    setBuildingOrder(prev => {
      const existing = prev.find(p => p.id === item.id);
      if (existing) {
        return prev.map(p => p.id === item.id ? {...p, quantity: p.quantity + quantity} : p);
      }
      return [...prev, { ...item, quantity }];
    });
  };

  const placeOrder = async () => {
    if (buildingOrder.length === 0) return;
    
    try {
      const total = buildingOrder.reduce((sum, item) => sum + (item.price * item.quantity), 0);
      
      // Create order data (order_number will be generated by the API)
      const orderData: CreateOrderRequest = {
        items: buildingOrder,
        total
      };

      const response = await fetch('/api/orders', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(orderData)
      });

      if (!response.ok) throw new Error('Failed to place order');

      setBuildingOrder([]);
      await fetchOrders(); // Refresh orders
      
    } catch (err) {
      setError('Failed to place order');
      console.error(err);
    }
  };

  const updateOrderStatus = async (orderId: string, status: Order['status']) => {
    try {
      const updateData: UpdateOrderRequest = { status };

      const response = await fetch(`/api/orders/${orderId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updateData)
      });

      if (!response.ok) throw new Error('Failed to update order');

      // For served orders, immediately update local state for instant UI feedback
      // and also force a refresh to ensure consistency with the backend
      if (status === 'served') {
        setOrders(prevOrders => prevOrders.filter(order => order.id !== orderId));
        setPendingOrdersCount(prev => prev - 1);
        await fetchDailySales();
        
        // Force an immediate refresh to ensure UI is in sync with backend
        setTimeout(() => {
          fetchOrders();
        }, 100);
      } else {
        await fetchOrders(); // Refresh orders for other status changes
      }
      
    } catch (err) {
      setError('Failed to update order');
      console.error(err);
    }
  };

  const deleteOrder = async (orderId: string) => {
    try {
      const response = await fetch(`/api/orders/${orderId}`, {
        method: 'DELETE'
      });

      if (!response.ok) throw new Error('Failed to delete order');

      await fetchOrders(); // Refresh orders
      
    } catch (err) {
      setError('Failed to delete order');
      console.error(err);
    }
  };

  const saveEditedOrder = async () => {
    if (!editingOrder || editingOrder.items.length === 0) {
      if (editingOrder) await deleteOrder(editingOrder.id);
      setEditingOrder(null);
      return;
    }

    try {
      const updateData: UpdateOrderRequest = {
        items: editingOrder.items,
        total: editingOrder.total
      };

      const response = await fetch(`/api/orders/${editingOrder.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updateData)
      });

      if (!response.ok) throw new Error('Failed to save order');

      setEditingOrder(null);
      await fetchOrders(); // Refresh orders
      
    } catch (err) {
      setError('Failed to save order');
      console.error(err);
    }
  };

  const removeItemFromBuildingOrder = (itemId: number) => {
    setBuildingOrder(prev => prev.filter(item => item.id !== itemId));
  };

  const updateBuildingOrderItemQuantity = (itemId: number, newQuantity: number) => {
    if (newQuantity <= 0) {
      // Remove item if quantity is 0 or less
      setBuildingOrder(prev => prev.filter(item => item.id !== itemId));
    } else {
      // Update quantity
      setBuildingOrder(prev => prev.map(item => 
        item.id === itemId ? { ...item, quantity: newQuantity } : item
      ));
    }
  };

  const removeItemFromOrder = async (orderId: string, itemId: number) => {
    try {
      const orderToUpdate = orders.find(order => order.id === orderId);
      if (!orderToUpdate) return;

      const updatedItems = orderToUpdate.items.filter(item => item.id !== itemId);
      const total = updatedItems.reduce((sum, item) => sum + (item.price * item.quantity), 0);

      const updateData: UpdateOrderRequest = {
        items: updatedItems,
        total
      };

      const response = await fetch(`/api/orders/${orderId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updateData)
      });

      if (!response.ok) throw new Error('Failed to remove item from order');

      await fetchOrders(); // Refresh orders
      
    } catch (err) {
      setError('Failed to remove item from order');
      console.error(err);
    }
  };

  const editOrder = (order: Order) => {
    setEditingOrder(order);
  };

  const cancelEdit = () => {
    setEditingOrder(null);
  };

  const updateEditingOrderItem = (itemId: number, newQuantity: number) => {
    if (!editingOrder) return;
    
    if (newQuantity <= 0) {
      // Remove item if quantity is 0 or less
      const updatedItems = editingOrder.items.filter(item => item.id !== itemId);
      const total = updatedItems.reduce((sum, item) => sum + (item.price * item.quantity), 0);
      setEditingOrder({ ...editingOrder, items: updatedItems, total });
    } else {
      // Update quantity
      const updatedItems = editingOrder.items.map(item => 
        item.id === itemId ? { ...item, quantity: newQuantity } : item
      );
      const total = updatedItems.reduce((sum, item) => sum + (item.price * item.quantity), 0);
      setEditingOrder({ ...editingOrder, items: updatedItems, total });
    }
  };

  const addItemToEditingOrder = (item: MenuItem) => {
    if (!editingOrder) return;
    
    const existingItem = editingOrder.items.find(i => i.id === item.id);
    let updatedItems;
    
    if (existingItem) {
      updatedItems = editingOrder.items.map(i => 
        i.id === item.id ? { ...i, quantity: i.quantity + 1 } : i
      );
    } else {
      updatedItems = [...editingOrder.items, { ...item, quantity: 1 }];
    }
    
    const total = updatedItems.reduce((sum, item) => sum + (item.price * item.quantity), 0);
    setEditingOrder({ ...editingOrder, items: updatedItems, total });
  };

  // Sales report functions
  const generateSalesReport = async () => {
    try {
      const response = await fetch(`/api/sales-report?startDate=${startDate}&endDate=${endDate}`);
      if (!response.ok) throw new Error('Failed to generate sales report');
      const data = await response.json();
      setSalesReport(data);
    } catch (err) {
      setError('Failed to generate sales report');
      console.error(err);
    }
  };

  const openReportModal = () => {
    setIsReportModalOpen(true);
    // Set default date range to current month
    const today = new Date();
    const firstDay = new Date(today.getFullYear(), today.getMonth(), 1);
    const lastDay = new Date(today.getFullYear(), today.getMonth() + 1, 0);
    
    setStartDate(firstDay.toISOString().split('T')[0]);
    setEndDate(lastDay.toISOString().split('T')[0]);
  };

  const closeReportModal = () => {
    setIsReportModalOpen(false);
    setSalesReport(null);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-100 flex items-center justify-center">
        <div className="text-center">
          <ChefHat className="w-12 h-12 mx-auto mb-4 animate-pulse" />
          <div>Loading...</div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-100 flex items-center justify-center">
        <div className="text-center text-red-600">
          <div className="text-xl font-bold mb-2">Error</div>
          <div>{error}</div>
          <button 
            onClick={() => window.location.reload()} 
            className="mt-4 px-4 py-2 bg-red-600 text-white rounded w-full sm:w-auto"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100 p-4 max-w-md mx-auto">
      {/* Header */}
      <div className="bg-gradient-to-r from-red-600 to-red-800 rounded-lg shadow-lg p-4 mb-4">
        <div className="flex flex-col sm:flex-row justify-between items-center gap-3">
          <div className="flex items-center gap-3">
            <img src="/logo.png" alt="Logo" className="w-17 h-17 mb-4" />
          </div>
          <div className="flex items-center gap-3">
            <a 
              href="/chef" 
              className="p-2 bg-white text-red-600 rounded-lg text-sm hover:bg-gray-100 transition-colors shadow-md flex items-center gap-1"
              title="Chef Dashboard"
            >
              <span className="hidden sm:inline"></span>
              👨‍🍳
            </a>
            <div className="bg-white/20 backdrop-blur-sm rounded-lg p-2">
              <div className="text-xs text-white/90">Pending</div>
              <div className="text-lg font-bold text-white">{pendingOrdersCount}</div>
            </div>
            <div className="bg-white/20 backdrop-blur-sm rounded-lg p-2">
              <div className="text-xs text-white/90">Sales</div>
              <div className="text-lg font-bold text-white">₹{dailySales}</div>
            </div>
            <button
              onClick={openReportModal}
              className="p-2 bg-white text-red-600 rounded-lg hover:bg-gray-100 transition-colors shadow-md"
              title="Sales Report"
            >
              <BarChart3 className="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>

      {/* Building Order Section */}
      {buildingOrder.length > 0 && (
        <div className="bg-red-100 rounded-lg p-4 mb-4 border-2 border-red-300">
          <h3 className="font-semibold text-red-900 mb-2">Building Order:</h3>
          {buildingOrder.map(item => (
            <div key={item.id} className="flex justify-between items-center py-2 border-b border-red-300">
              <span className="text-red-900 font-medium">{item.name}</span>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => updateBuildingOrderItemQuantity(item.id, item.quantity - 1)}
                  className="w-6 h-6 bg-red-600 text-white rounded flex items-center justify-center hover:bg-red-700 transition-colors text-sm"
                >
                  -
                </button>
                <span className="w-6 text-center font-semibold text-red-900 text-sm">{item.quantity}</span>
                <button
                  onClick={() => updateBuildingOrderItemQuantity(item.id, item.quantity + 1)}
                  className="w-6 h-6 bg-red-600 text-white rounded flex items-center justify-center hover:bg-red-700 transition-colors text-sm"
                >
                  +
                </button>
                <span className="font-medium text-red-900 w-16 text-right">₹{item.price * item.quantity}</span>
                <button
                  onClick={() => removeItemFromBuildingOrder(item.id)}
                  className="p-2 text-red-600 hover:text-red-800 hover:bg-red-100 rounded transition-colors"
                  title="Remove item"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            </div>
          ))}
          <div className="border-t border-red-300 pt-2 mt-2 flex justify-between items-center">
            <span className="font-bold text-red-900">
              Total: ₹{buildingOrder.reduce((sum, item) => sum + (item.price * item.quantity), 0)}
            </span>
            <button 
              onClick={placeOrder}
              className="bg-red-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-red-700"
            >
              Place Order
            </button>
          </div>
        </div>
      )}

      {/* Edit Order Modal */}
      {editingOrder && (
        <div className="fixed inset-0 bg-black bg-opacity-60 backdrop-blur-sm flex items-center justify-center p-4 z-50 transition-opacity duration-300">
          <div className="bg-white rounded-xl p-6 max-w-md w-full max-h-[85vh] overflow-y-auto shadow-2xl border border-gray-200 transform transition-all duration-300 scale-100">
            {/* Header */}
            <div className="flex justify-between items-center mb-6 pb-4 border-b border-gray-200">
              <div>
                <h2 className="text-2xl font-bold text-gray-900 bg-gradient-to-r from-red-600 to-red-800 bg-clip-text text-transparent">
                  Edit Order #{editingOrder.order_number}
                </h2>
                <p className="text-sm text-gray-600 mt-1">Modify items and quantities</p>
              </div>
              <button
                onClick={cancelEdit}
                className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-full transition-colors duration-200"
                title="Cancel"
              >
                <X className="w-6 h-6" />
              </button>
            </div>
            
            {/* Current Items Section */}
            <div className="mb-6">
              <h3 className="font-semibold text-gray-900 mb-4 text-lg flex items-center gap-2">
                <div className="w-2 h-2 bg-red-500 rounded-full"></div>
                Current Items
              </h3>
              <div className="space-y-3">
                {editingOrder.items.map(item => (
                  <div key={item.id} className="flex justify-between items-center p-4 bg-gray-50 rounded-lg border border-gray-200 hover:bg-gray-100 transition-colors duration-200">
                    <div className="flex-1 min-w-0">
                      <span className="text-gray-900 font-medium text-sm block truncate">{item.name}</span>
                      <span className="text-gray-600 text-xs">₹{item.price} each</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="flex items-center gap-2 bg-white rounded-full p-1 shadow-sm">
                        <button
                          onClick={() => updateEditingOrderItem(item.id, item.quantity - 1)}
                          className="w-8 h-8 bg-gray-100 text-gray-700 rounded-full flex items-center justify-center hover:bg-gray-200 transition-colors duration-200 font-semibold text-lg"
                          title="Decrease quantity"
                        >
                          -
                        </button>
                        <span className="w-8 text-center font-bold text-gray-900 text-sm">{item.quantity}</span>
                        <button
                          onClick={() => updateEditingOrderItem(item.id, item.quantity + 1)}
                          className="w-8 h-8 bg-red-100 text-red-700 rounded-full flex items-center justify-center hover:bg-red-200 transition-colors duration-200 font-semibold text-lg"
                          title="Increase quantity"
                        >
                          +
                        </button>
                      </div>
                      <button
                        onClick={() => updateEditingOrderItem(item.id, 0)}
                        className="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded-full transition-colors duration-200"
                        title="Remove item"
                      >
                        <Trash2 className="w-5 h-5" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Add Items Section */}
            <div className="mb-6">
              <h3 className="font-semibold text-gray-900 mb-4 text-lg flex items-center gap-2">
                <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                Add Items
              </h3>
              <div className="grid grid-cols-2 gap-3">
                {menuItems.map(item => (
                  <button
                    key={item.id}
                    onClick={() => addItemToEditingOrder(item)}
                    className="bg-gradient-to-r from-red-500 to-red-700 hover:from-red-600 hover:to-red-800 text-white p-3 rounded-lg font-medium text-sm transition-all duration-200 transform hover:scale-105 shadow-md hover:shadow-lg"
                  >
                    <div className="font-semibold text-xs leading-tight">{item.name}</div>
                    <div className="text-xs opacity-90 mt-1">₹{item.price}</div>
                  </button>
                ))}
              </div>
            </div>

            {/* Total and Action Buttons */}
            <div className="border-t border-gray-200 pt-6">
              <div className="flex justify-between items-center mb-6">
                <div>
                  <div className="text-sm text-gray-600">Order Total</div>
                  <div className="text-2xl font-bold text-gray-900">
                    ₹{editingOrder.total}
                  </div>
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={cancelEdit}
                    className="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg font-medium hover:bg-gray-300 transition-all duration-200 transform hover:scale-105 border border-gray-300"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={saveEditedOrder}
                    className="px-6 py-3 bg-gradient-to-r from-red-600 to-red-800 text-white rounded-lg font-medium hover:from-red-700 hover:to-red-900 transition-all duration-200 transform hover:scale-105 shadow-md hover:shadow-lg flex items-center gap-2"
                  >
                    <Save className="w-5 h-5" />
                    Save Changes
                  </button>
                </div>
              </div>
              
              {editingOrder.items.length === 0 && (
                <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded">
                  <p className="text-sm text-yellow-800">
                    ⚠️ This order will be deleted if you save without any items.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Menu Grid */}
      <div className="bg-white rounded-lg shadow-lg p-4 mb-4">
        <h2 className="font-semibold text-gray-800 text-lg mb-4">Menu Items</h2>
        
        <div className="grid grid-cols-2 gap-3">
          {menuItems.map(item => (
            <button
              key={item.id}
              onClick={() => addToOrder(item, 1)}
              className="w-full p-4 rounded-lg text-center font-medium min-h-[90px] flex flex-col justify-center transition-all duration-300 shadow-md hover:shadow-lg bg-gradient-to-br from-red-600 to-red-800 hover:from-red-700 hover:to-red-900 cursor-pointer hover:scale-105"
            >
              <div className="font-semibold text-sm leading-tight px-1 overflow-hidden" style={{ 
                display: '-webkit-box',
                WebkitLineClamp: 2,
                WebkitBoxOrient: 'vertical'
              }}>{item.name}</div>
              <div className="text-xs opacity-90 mt-2 bg-white/20 rounded px-1 py-0.5">₹{item.price}</div>
            </button>
          ))}
        </div>
      </div>

      {/* Order Queue */}
      <div className="bg-white rounded-lg shadow-lg p-4">
        <h2 className="font-semibold text-gray-800 mb-4 text-lg flex items-center gap-2">
          <Clock className="w-6 h-6 text-red-600" />
          Order Queue ({orders.length})
        </h2>
        
        {orders.length === 0 ? (
          <div className="text-center py-12 text-gray-500 bg-gray-50 rounded-lg">
            <ChefHat className="w-16 h-16 mx-auto mb-4 opacity-50" />
            <div className="text-lg">No orders in queue</div>
            <div className="text-sm mt-2">Start building orders from the menu!</div>
          </div>
        ) : (
          <div ref={ordersContainerRef} className="mt-2" style={{ maxHeight: '400px', overflowY: 'auto' }}>
            <div className="space-y-4 pr-1">
              {orders.map(order => (
                <div 
                  key={order.id} 
                  className="p-5 rounded-lg border-l-4 border-red-500 bg-gradient-to-r from-red-50 to-white shadow-md hover:shadow-lg transition-all duration-300 cursor-pointer"
                  onClick={() => handleOrderClick(order)}
                >
                  <div className="flex justify-between items-start mb-3">
                    <div className="flex items-center gap-3">
                      <Clock className="w-6 h-6 text-red-700" />
                      <span className="font-bold text-xl text-red-900">#{order.order_number}</span>
                      <span className={`px-3 py-1 rounded-full text-sm font-semibold ${
                        order.status === 'preparing' 
                          ? 'bg-yellow-200 text-yellow-900' 
                          : order.status === 'ready' 
                          ? 'bg-green-200 text-green-900'
                          : order.status === 'served'
                          ? 'bg-red-200 text-red-900'
                          : 'bg-orange-200 text-orange-900'
                      }`}>
                        {order.status}
                      </span>
                    </div>
                    <div className="text-right">
                      <div className="font-bold text-xl text-red-900">₹{order.total}</div>
                    </div>
                  </div>
                  
                  <div className="mb-4">
                    {order.items.map(item => (
                      <div key={item.id} className="flex justify-between items-center text-sm text-red-800 py-2 border-b border-red-100 last:border-b-0">
                        <span className="font-medium">{item.quantity}x {item.name}</span>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            removeItemFromOrder(order.id, item.id);
                          }}
                          className="p-2 text-red-600 hover:text-red-800 hover:bg-red-100 rounded-full transition-colors"
                          title="Remove item"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    ))}
                  </div>
                  
                  <div className="flex gap-2">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        editOrder(order);
                      }}
                      className="px-3 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg font-medium transition-colors flex items-center gap-1 text-sm"
                      title="Edit order"
                    >
                      <Edit2 className="w-3 h-3" />
                      Edit
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        updateOrderStatus(order.id, 'served');
                      }}
                      className="flex-1 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg font-medium transition-colors text-sm"
                    >
                      Served
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        deleteOrder(order.id);
                      }}
                      className="px-3 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg font-medium transition-colors flex items-center gap-1 text-sm"
                      title="Delete order"
                    >
                      <Trash2 className="w-3 h-3" />
                      Delete
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Sales Report Modal */}
      {isReportModalOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg p-6 max-w-md w-full max-h-[80vh] overflow-y-auto shadow-xl">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl font-bold text-gray-900">Sales Report</h2>
              <button
                onClick={closeReportModal}
                className="p-2 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded"
                title="Close"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="mb-4">
              <div className="grid grid-cols-2 gap-3 mb-3">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
                  <input
                    type="date"
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    className="w-full p-2 border border-gray-300 rounded text-gray-900 bg-white"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">End Date</label>
                  <input
                    type="date"
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    className="w-full p-2 border border-gray-300 rounded text-gray-900 bg-white"
                  />
                </div>
              </div>
              
              <button
                onClick={generateSalesReport}
                className="w-full bg-red-600 hover:bg-red-700 text-white py-2 px-4 rounded font-medium transition-colors"
              >
                Generate Report
              </button>
            </div>

            {salesReport && (
              <div className="border-t border-gray-200 pt-4">
                <h3 className="font-semibold text-gray-900 mb-3">Report Results:</h3>
                
                <div className="space-y-3">
                  <div className="bg-green-50 p-3 rounded">
                    <div className="text-sm text-green-800">Total Revenue</div>
                    <div className="text-lg font-bold text-green-900">₹{salesReport.total_revenue || 0}</div>
                  </div>
                  
                  <div className="bg-red-50 p-3 rounded">
                    <div className="text-sm text-red-800">Total Orders</div>
                    <div className="text-lg font-bold text-red-900">{salesReport.total_orders || 0}</div>
                  </div>
                  
                  {salesReport.daily_sales && salesReport.daily_sales.length > 0 && (
                    <div>
                      <h4 className="font-medium text-gray-900 mb-2">Daily Breakdown:</h4>
                      <div style={{ maxHeight: '200px', overflowY: 'auto' }}>
                        <div className="space-y-2">
                          {salesReport.daily_sales.map((day: any) => (
                            <div key={day.date} className="flex justify-between items-center p-2 bg-gray-50 rounded">
                              <span className="text-sm text-gray-700">{new Date(day.date).toLocaleDateString()}</span>
                              <span className="font-medium text-gray-900">₹{day.revenue}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                  
                  {salesReport.top_items && salesReport.top_items.length > 0 && (
                    <div>
                      <h4 className="font-medium text-gray-900 mb-2">Top Selling Items:</h4>
                      <div className="space-y-2">
                        {salesReport.top_items.slice(0, 5).map((item: any, index: number) => (
                          <div key={index} className="flex justify-between items-center p-2 bg-orange-50 rounded">
                            <span className="text-sm text-orange-800">{item.name}</span>
                            <span className="font-medium text-orange-900">{item.quantity} sold</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Order Detail Popup */}
      {viewingOrder && (
        <div className="fixed inset-0 bg-black bg-opacity-5 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg p-6 max-w-md w-full max-h-[80vh] overflow-y-auto shadow-xl">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl font-bold text-gray-900">Order #{viewingOrder.order_number}</h2>
              <button
                onClick={closeOrderPopup}
                className="p-2 text-gray-600 hover:text-gray-800 hover:bg-gray-100 rounded"
                title="Close"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="mb-4">
              <div className="flex justify-between items-center mb-3">
                <span className="font-semibold text-gray-900">Status:</span>
                <span className={`px-3 py-1 rounded-full text-sm font-semibold ${
                  viewingOrder.status === 'preparing' 
                    ? 'bg-yellow-200 text-yellow-900' 
                    : viewingOrder.status === 'ready' 
                    ? 'bg-green-200 text-green-900'
                    : viewingOrder.status === 'served'
                    ? 'bg-red-200 text-red-900'
                    : 'bg-orange-200 text-orange-900'
                }`}>
                  {viewingOrder.status}
                </span>
              </div>
              
              <div className="flex justify-between items-center mb-3">
                <span className="font-semibold text-gray-900">Total:</span>
                <span className="font-bold text-xl text-red-900">₹{viewingOrder.total}</span>
              </div>
            </div>

            <div className="mb-4">
              <h3 className="font-semibold text-gray-900 mb-3">Items:</h3>
              {viewingOrder.items.map(item => (
                <div key={item.id} className="flex justify-between items-center py-2 border-b border-gray-200">
                  <span className="text-gray-900 font-medium">{item.quantity}x {item.name}</span>
                  <span className="font-medium text-gray-900">₹{item.price * item.quantity}</span>
                </div>
              ))}
            </div>

            <div className="border-t border-gray-200 pt-4">
              <button
                onClick={closeOrderPopup}
                className="w-full px-6 py-3 bg-red-600 text-white rounded-lg font-medium hover:bg-red-700 transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CafeOrderSystem;
